### ISSUE TITLE
Trying to use with Ollama

### ISSUE THREAD

**Issue by jeremyandrews** [tensorzero/tensorzero#411]
I'm hoping to use tensorzero as a load balancer between several local Ollama instances. To start, I'm just trying to get it working. I've got the following environment configuration:

```
me@ai:~/tensorzero_config$ cat .env 
OPENAI_API_KEY=foo
CLICKHOUSE_URL=http://10.10.10.10:8123/tensorzero
```

And the following tensorzer.toml configuration file:
```
me@ai:~/tensorzero_config$ cat tensorzero.toml
[models.llama3]
routing = ["ollama1"]

[models.llama3.providers.ollama1]
type = "openai"
api_base = "http://10.10.10.11:11434"
model_name = "llama3.1:70b-instruct-q8_0"

[functions.generate_response]
type = "chat"

[functions.generate_response.variants.ollama1]
type = "chat_completion"
model = "llama3"
```

I am able to access Ollama at http://10.10.10.11:11434. I am able to access ClickHouse at 10.10.10.10:8123 (and the migrations successfully run.)

I rebuild things with the following commands, and there are no errors:
```
sudo docker stop tensorzero-gateway
sudo docker rm tensorzero-gateway
sudo docker run --name tensorzero-gateway --restart always -v /home/me/tensorzero_config:/app/config --env-file /home/me/tensorzero_config/.env -p 11434:3000 -d tensorzero/gateway
sudo docker logs tensorzero-gateway
```

If I load http://10.10.10.10:11434/health I get the following output:
```
{"gateway":"ok","clickhouse":"ok"}
```

If I load http://10.10.10.10:11434 I get a 404. The same if I go to http://10.10.10.10:11434/api/generate

What is the URL I should be specifying to load the Ollama API through tensorzero?

**Comment by jeremyandrews** [comment]
I suspect my issue is: I was wanting to use the OpenAI API format through this as a proxy, but it seems that's not how it works?

**Comment by GabrielBianconi** [comment]
Hi @jeremyandrews - the TensorZero API is slightly different from the OpenAI API. We made the change because this interface unlocks features that are helpful for optimization and other LLM engineering workflows (e.g. using schemas for your prompts).

(See "Why doesn't the TensorZero Gateway have an OpenAI-compatible API?" on our [FAQ](https://www.tensorzero.com/docs/faq) for more info.)

---

For completeness, I just tested the following setup on a Mac:

1) `ollama pull llama3.1`

2) `tensorzero.toml`

```toml
[models.llama_3_1]
routing = ["ollama"]

[models.llama_3_1.providers.ollama]
type = "openai"
api_base = "http://host.docker.internal:11434/v1/"  # T0 Gateway is running in Docker, Ollama is running on host directly
model_name = "llama3.1"

[functions.my_function]
type = "chat"

[functions.my_function.variants.llama_3_1]
type = "chat_completion"
model = "llama_3_1"
```

3) Launch T0 Gateway Docker container (see Quick Start for example)

4) Run an inference against it:

```bash
curl -X POST http://localhost:3000/inference \
  -H "Content-Type: application/json" \
  -d '{
    "function_name": "my_function",
    "input": {
      "system": "You are a helpful assistant that speaks in haikus.",
      "messages": [
        {
          "role": "user",
          "content": "What is the capital of Japan?"
        }
      ]
    }
  }'
```

(You can also use the Python client.)

Output:

```
{"inference_id":"0192e33e-7409-7843-8875-4ac9b58e548a","episode_id":"0192e33e-6ef5-7f71-abfc-57624228d8a2","variant_name":"llama_3_1","content":[{"type":"text","text":"Tokyo's shining face\nCapital city, proud and bright\nJapan's heart abides"}],"usage":{"input_tokens":34,"output_tokens":19}}
```

---

If you want to use multiple Ollama instances as fallbacks (in case inference fails), you can add more providers to the same model in the config above.

If you want to always distribute traffic (load balancing), you can set up multiple variants for the function and set up a separate model+provider for each variant. You can optionally also specify a weight for each variant.

For more information, see our [Quick Start](https://www.tensorzero.com/docs/gateway/quickstart) and [Comprehensive Tutorial](https://www.tensorzero.com/docs/gateway/tutorial) (especially the "Experimentation" section).

---

I'll close this issue for now, but please feel free to reopen it if you have any issues.

**Comment by jeremyandrews** [comment]
Thank you!
