### ISSUE TITLE
Python client's `_prepare_inference_request` causes side-effects

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#434]
Thanks @LeOndaz:

> `_prepare_inference_request` has a potential side effect, in the code quoted below:
>
> ```python
> # Convert content blocks to dicts if necessary
> for message in input.get("messages", []):
>     if isinstance(message["content"], list):
>         message["content"] = [
>             item.to_dict() if hasattr(item, "to_dict") else item
>             for item in message["content"]
>         ]
> ```
>
> This code's problem happens **only if it works**. Since `messages` is a list and it's passed by reference in Python, the code is modifying the list in place, which reflects in the user's `input` dict. This can potentially cause side-effects if the user is processing the `input` after doing the inference, or if they're just saving it to the database, they will save a malformed input.

**Comment by LeOndaz** [comment]
Hey, thanks! glad it helped

I wonder if it would help to have the `input` a more strictly typed Dict (`typing.TypedDict`) so that you are sure it has the `messages` key statically, or even a more generic `Mapping`

Also the `isinstance(x, list)` logic can be generalized to `Iterable` (not Mapping though) this way if the user has a tuple/set, he wouldn't spend some memory on making it a list first, since `_prepare_inference_request` is not really using any `list` specific operations, what do you think?
